# Generated by Django 5.0.2 on 2024-02-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='exit_date',
            field=models.DateTimeField(null=True),
        ),
    ]
