# Generated by Django 5.0.2 on 2024-02-28 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_alter_parkmovement_exit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
