# Generated by Django 5.0.2 on 2024-02-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_alter_parkmovement_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
