# Generated by Django 5.0.2 on 2024-02-28 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_alter_parkmovement_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='api_rest.contract'),
        ),
    ]
