# Generated by Django 5.0.2 on 2024-02-29 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_alter_parkmovement_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkmovement',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='api_rest.vehicle'),
        ),
    ]
